---
bibliography: references.bib
---

# Introduction {#intro}


## Essential intent

## QMEL flywheel


## Readings

See the next chapter for more detail on our lab culture and philosophy. We are motivated heavily by the following two papers - which provide a blueprint for how we think about the way we do our work:

- Our path to better science in less time using open data science tools [@lowndes2017]
- Good enough practices in scientific computing [@wilson2017]

\[To come: recommended reading list\]






## Shared lab resources

We also share our institutional knowledge through our lab-chat github 'issues' repository. This is a community-driven troubleshooting resource, please contribute!

We maintain a lab Sharepoint folder for lab publications, presentations, photos, CVs, etc. Please make use of these so that others in the lab can make fair use of our work.

- [Lab Sharepoint/One Drive](https://universitysystemnh.sharepoint.com/teams/QuantMarineEcologyLab/SitePages/ProjectHome.aspx)

## References

