# Undergrads and interns {#training-undergrads-and-interns}


## Welcome

Welcome to QMEL! We typically host very few undergraduate researchers or interns. During the academic year, we might have 1-2 students completing a thesis or independent project. 

## Expectations

Undergraduates play a critical role in QMEL. The lab has several ongoing research projects led by either Professor White or another senior member of the lab (including graduate students and postdocs). Undergraduates interested in working in the lab should have a genuine interest in the research questions and be interested in developing quantitative (e.g., math, statistics, computer programming) skills.

Research Phases: There are three phases at which undergraduates can be involved in research within QMEL. The different phases represent different levels of research experience, independence, and responsibility. Most students start as research assistants. Not all students move through all three levels of involvement.

-   Research Apprentice: The first stage of involvement for an undergraduate is as a research apprentice. At this stage, an undergraduate joins a research team in the lab. The goal is to get caught up on the current progress of the team. This includes reading scientific papers, learning necessary tools (e.g., R programming), and meeting regularly with team members. This phase continues until Professor White and the research team agree the student is ready to become a more active and contributing member to the lab. This phase typically last one semester or year.
-   Research Assistant: Following their apprenticeship, students are expected to contribute in more significant ways to the research team. This can involve collecting and analyzing data, manuscript writing, conducting experiments, and so forth. The goal during this phase is to present work at a scientific conference or submit a manuscript to a peer-reviewed scientific journal.
-   Research Associate: The final phase of involvement in the lab is for students who have presented their work at a conference or been involved in the submission of a manuscript (see above). This phase involves more leadership and independence. Students at this level define team goals, help mentor new team members, and meet regularly with Professor White. This phase in the lab is very similar to being a graduate student in the lab.

During your time as a undergraduate researcher in the QEML, you will
have several responsibilities:

- Send mentors weekly email updates on Fridays by 5pm describing briefly what you’ve been working on, what you plan to do the following week, and any questions or troubles you had. Important things to include: projects you’ve worked on, broken equipment, storage/equipment conflicts, if your data looks weird.
- Keep weekly notes, especially of meetings with mentors. 
- Prepare a monthly blog post of what you are working on.
- Attend lab meetings. The entire lab assembles approximately once a week to discuss our research. Generally, the person leading the lab meeting will distribute reading materials in advance. You should read these materials and come prepared to participate actively in the discussion.
- Maintain a lab notebook and stay organized. There is a lot of overlap in projects, and it is essential that you keep track of your work. This includes updating the data spreadsheets and lab notebooks immediately. Someone else should be able to step into your role at any moment and be able to get up to speed quickly.
- Read background literature. A key part to your development as a scientist
- Communicate, communicate, communicate. Many of the issues that arise in research are simply because of a lack of communication. It is critical that you communicate early and often on issues or concerns that you may be experiences.
- Be independent. I am periodically away, and I expect you to get things done well without me. Ask questions when I am around, but don’t be afraid to try to do the detective work on your own if I am not. We have a helpful, experienced lab, so know that folks other than me may be excellent resources.
- Keep up with your other responsibilities. As an undergraduate, you have many other obligations. This can include coursework, jobs, family, and more.


## Summer field work

Some interns join the lab primarily in summers and may be involved in field work. You'll receive more details on specifics of field work relevant to your position. Here are a few general points though.

### Packing list

- Hat
- Sunglasses
- Bag for the field/office (a small backpack or something)
- Personal laptop if you have one
- Comfortable outdoor or athletic clothing (usually made of synthetic fabric). If possible, you may want to bring some comfortable, thinner long pants and long sleeve shirts because there are a lot of ticks and poison ivy up here.
- Reusable water bottle
- Medications (and let mentors know of any medical concerns generally)
