# Graduate students {#training-grad-students}



## Academics

Specific requirements of MS and PhD students depend on whether they are enrolled in Marine Biology or Integrative Bioloy. These requirements are updated more regularly in [internal departmental documents](https://universitysystemnh.sharepoint.com/teams/UNHDBS/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FUNHDBS%2FShared%20Documents%2FGraduate%20Students&viewid=4c4a5c2a%2D829f%2D4549%2Db195%2D31d0fb25b563). The goal here is lay out requirements, coursework, and timelines more specific to QMEL. There are also details about requirements at the [Graduate School level available](https://catalog.unh.edu/graduate/academic-regulations-degree-requirements/degree-requirements/#text).

Learning outcomes of a graduate degree from QMEL

1. TBD
2. TBD

Key competencies

1. 
2. 

### MS program


### PhD program

Responsible Conduct of Research

As a land-­grant institution, the University of New Hampshire (UNH) is accountable to New Hampshire residents and to the University community to ensure the ethical and safe conduct of research and scholarly activity. As an institution of higher education that prides itself on extensive research endeavors and the involvement of undergraduates and graduate students in research projects, UNH has an obligation to teach and actively promote integrity in research and scholarship.

To fulfill its obligations, UNH has embarked on a program on the responsible conduct of [research and scholarly activity (RCR)](http://www.unh.edu/research/responsible-conduct-research-scholarly-activity) to:

    Raise the consciousness of faculty, staff, and students regarding the ethical and responsible conduct of research and scholarly activity;
    Establish a knowledge base that defines normative and/or professional behavior to assist faculty, staff, and students in making ethical and responsible decisions in the conduct of research and scholarly activity; and
    Foster an institutional culture of integrity in research and scholarly activity.

To support these efforts, the Graduate Council has mandated that all incoming Ph.D. students complete RCR training approved by the Graduate School by the end of their first semester. For more information, [visit the RCR website](http://www.unh.edu/research/responsible-conduct-research-scholarly-activity).

#### PhD proposal

At the end of year one or early in year 2, you are expected to formally defend your PhD proposal. The proposal is an opportunity to formalize your PhD plan and receive feedback from the committee. Your PhD path will surely change along the way, so the proposal is exactly that---a proposal. Proposals in QMEL tend to be more detailed than those in other labs. In particular, we write propoosals in "manuscript format" where each chapter is described with an introduction and methods section. 

MORE HERE


#### PhD Qualifying Exam 

The committee should be provided with the research proposal ahead of time, because this will shape what they decide is important to cover in the qualifying exams. Questions about the proposal are highly appropriate as part of the oral exam. The qualifying exam typically happens at the end of year 2 or the start of year 3. If the qualifying exam has not been completed by the end of year 3, a student may be placed on probation. 


##### Outline of process for qualifying exams (written and oral components):

- The Student schedules dates for the (a) written and (b) oral portions of the exam
 + The written portion does not require committee members’ presence. It should be completed in time for committee members to review answers before the oral, around two weeks in advance.
 + The oral portion requires all members’ participation (in person or via zoom).
 + Use meeting schedulers like when2meet or doodle to identify a two-hour block that works for the oral exam. It is advised you schedule this far in advance, ideally when your committee members have their schedules for the next semester (2-3 months is ideal).
- The Student chooses three areas of specialization in consultation with her committee
 + Discuss and agree in advance whether the exam is open- or closed-book, time limits, and expected length of written answers (usually 2-5 pages each)
 + Committee members each submit 2-3 possible questions  to Easton, who selects and provides them to The Student on the agreed date(s) – often, one question per day within a single week
 + The Student answers selected questions in essay form and returns those answers to Easton
 + Easton circulates all answers to all committee members
- Oral exam: about 2 hours
 + Committee members take turns asking The Student questions (including but not limited to the written exam and research proposal; general knowledge in relevant areas is also appropriate/fair game)
 + The Student leaves the room and the committee decides whether she has earned a pass, conditional pass (needs to re-do some portion of the exam), or fail. 
 + She comes back, we tell her the decision, and go on from there.
 + Once she has passed the exam, The Student fills out paperwork, Easton signs it, and it goes to Lisa Buchalski and thence to the graduate school. This includes nominating her Doctoral Dissertation Committee, which may look a lot like her current Guidance Committee.
- There are two forms
 + [Grad school Doctoral Candidacy form](https://universitysystemnh.sharepoint.com/teams/COLSASocialMedia/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FCOLSASocialMedia%2FShared%20Documents%2FWebsite%2Fdoctoral%2Dcandidacy%2Dform%2Epdf&parent=%2Fteams%2FCOLSASocialMedia%2FShared%20Documents%2FWebsite&p=true&ga=1) (only GPC and advisor sign)
 + [DBS Comprehensive Exam form](https://universitysystemnh.sharepoint.com/:b:/r/teams/UNHDBS/Shared Documents/Graduate Students/DBS Grad Forms/DBS_compexamform.pdf?csf=1&web=1&e=A8S2mN) (all committee members must sign)


##### Advice for qualifying exams

The candidacy/qualifying/comprehensive exam can seem intimidating. It will require you to take at least one month off your typical routine (maybe longer if you need to TA or have other commitments) to prepare. However, as long as you study you will pass. Easton and your committee will not have agreed to you scheduling Comps if they didn’t think you would be ready. 

Scheduling – Ideally, you will pass your Comps before the end of your fifth semester. Work backwards and figure out how much time you will need to schedule both orals and written exams and study. You will need to propose to your committee that you are ready to take Comps, ideally during a committee meeting so that your progress is fresh in their minds and you have a captive audience. Bonus points if you can make everyone take out their calendars during the meeting and schedule the orals then and there! If you need to email your committee instead, account for how long it will take for everyone to 1) agree that you are ready for Comps and 2) agree on a date and time. Ideally, do this 2-4 months in advance. 

Focal areas and Reading list– When planning on your study schedule, you should plan on doing all of your prep work before your writtens, not your orals. You will want to take a breahter/refocus a bit in between your writtens and orals, and having to play catchup is not ideal.

Around 6-8 weeks before your written exam week, write to each committee member to determine 1) what areas of focus they should question you on, and 2) suggested reading lists given these focal areas. Focus areas should be tailored to each committee member’s main disciplines and how they intersect with your work. You can start off with a list you and Easton decide on, and then see what they think. Along with the focal areas, you should solicit a reading list from your committee members. This reading list can be an enormous help in your studying, as the textbooks/review papers/seminal papers they suggest are likely to be different from the reading you’ve been doing for your proposal and individual experiments. They should send you somewhere between 5-15 resources. 

How to study – At least 4-6 weeks before your written exam date, you should have all meetings organized, reading material acquired, and focus areas agreed upon. Organization of your readings and notes is critical and highly personal – use what has worked for you historically. Notetaking programs like Notion and OneNote are highly customizable and use a reference manager to organize your resources (ideally in a separate “comps” folder). If it is helpful to you, calculate how many papers/pages you need to read a day – this will help you break down the intimidating stack of reading! 

Given the time limits you have during your written and oral exams, having a good recall of 1) what a certain paper is about (i.e. Levin and Paine 1974 is about disturbances in intertidal communities...) and 2) what papers you can cite or refer to on a given subject (Metabolic Theory of Ecology originated from  1997 West, Brown, and Enquist paper). They are not going to ask you about methodological details (generally), or a specific result. Instead, you should focus on the major conclusions, theories, patterns, models, trends, etc. That are discussed in each paper. This is why you will find yourself reading more review papers, textbooks, synthesis papers, etc. Than you probably normally do. 

Take notes, ideally both in the text of each paper and in a single document/program so that you can easily refer back to all your notes later. 

My master’s advisor once told me to follow the 6-6-6 rule... start studying six weeks before your exam date, six days a week, six hours a day. I don’t think working six days a week is at all necessary, but this structure can give you a general clue for how much time you should be spending. 














