# Lab leader {#training-lab-leader}

## Expectations of the Principal Investigator

The leader of QMEL is expected to:

-   Support you (scientifically, emotionally, financially)
-   Give you feedback on a timely basis, including feedback on project
    ideas, conference posters, talks, manuscripts, figures, grants
-   Be available in person and via online on a regular basis, including
    regular meetings to discuss your research (and anything else you’d
    like to discuss)
-   Give their perspective on where the lab is going, where the field is
    going, and tips about surviving and thriving in academia
-   Support your career development by introducing you to other
    researchers in the field, promoting your work at talks, writing
    recommendation letters for you, and letting you attend conferences
    as often as finances permit
-   Help you prepare for the next step of your career, whether it’s a
    post-doc, a faculty job, or a job outside of academia
-   Care for your emotional and physical well-being, and prioritize that
    above all else