# Producing quality work {#producing-quality-work}

For better or worse, publications are a key currency in science. They
are one of the main ways we track scientific progress and individual
production. Authorship on papers can be one of the most fraught topics
and is therefore often ignored until the last minute. This is a bad
strategy and only leads to resentment among co-authors. Therefore,
authorship (in terms of composition and order) should be determined at
the onset of the project. The specifics might change throughout the
project, but it is key to have a starting point to work with from the
start. The term “significant scientific contributions” is often used for
defining who should be included as an author. In this lab, we use the
definition from the International Committee of Medical Journal Editors
(<http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html>):
The ICMJE recommends that authorship be based on the following 4
criteria:

-   Substantial contributions to the conception or design of the work;
    or the acquisition, analysis, or interpretation of data for the
    work; AND
-   Drafting the work or revising it critically for important
    intellectual content; AND
-   Final approval of the version to be published; AND
-   Agreement to be accountable for all aspects of the work in ensuring
    that questions related to the accuracy or integrity of any part of
    the work are appropriately investigated and resolved. In addition,
    “the corresponding author is the one individual who takes primary
    responsibility for communication with the journal during the
    manuscript submission, peer review, and publication process”.

Thus, simply providing some data or providing minor comments on a
manuscript do not warrant authorship, but they should still be
acknowledged. Just because I am your advisor, does not mean I warrant
authorship on your publications. The same goes for your committee
members. There will likely be publications that you are involved with
that I have only a small part in. That being said, the most common order
(but by no means the only) for authorship in the lab is Grad Student
Lead, Other Contributors, with the PI as the last author. It is common
for the grad student lead and the PI to both be corresponding authors.



## Advice on writing

Key principles on writing in the lab

- Use active voice 
- Write clearly and concisely
- Avoid filler words, long sentences, and weak verbs

Here are some examples of the last bullet:

- Long sentences 
   - Example: “The connection between sedimentation and flow has been investigated in depth and if cleaning and flow rates are highly correlated this knowledge supports the pressures to maintain frequent cleaning implementations in aquaculture”
- Filler words
   - Example: “The uncertainties lie with how oysters and other bivalves will be influenced by these increased disruptions through the cleaning process." You could write, “The impact of increased cleaning disruptions on oysters and other bivalves is uncertain.”
   - Example: “For further identifying health of oysters, we used gaping behavior as a proxy due to its connection to respiration and feeding.” You could write, “To assess oyster health, we used gaping behavior as a proxy for respiration and feeding.” – this is a subtle shift, but a few less words makes the sense feel so much smoother
- Verb choice ([https://www.aje.com/arc/editing-tip-powerful-verbs/](https://www.aje.com/arc/editing-tip-powerful-verbs/) and [https://www.brandeis.edu/writing-program/resources/faculty/handouts/active-verbs-discussing-ideas.html](https://www.brandeis.edu/writing-program/resources/faculty/handouts/active-verbs-discussing-ideas.html))
   - Example: “…the connection to potential benefits have not been investigated." You could instead write “…the connection to potential benefits remains unexplored." Often verbs that rely on “have”  or “can” (which are helping (auxiliary) verbs) in the sentence indicate weak verbs.
   - Example: “Filter feeders landing on the surrounding cages can lead to declines in food abundances for the bivalves within." You could write, "Filter feeders landing on the surrounding cages can reduce food abundance for bivalves."
   - Example: “Biofouling is an additional factor associated with cleaning implementation and impede flow rates in cages” You could write "Biofouling contributes to cleaning challenges and reduces flow rates in cages."

As an academic, you are also now a professional writer. You get paid to think of ideas, test them, and then write about your findings. Writing can be one of the most important aspects of being a scientist, but it can also lead to a lot of pain. Why? Writing is hard by its nature. It is not natural and is a skill you have to develop and keep working on. I still read lots of books on writing and attend workshops. I also work with professional editors to help improve my own writing.  

You have to write consistently. Ideally, you would write every day for a set duration (say 30-60 minutes). I write a lot, not because I am a great writer, but because I am a consistent writer. If you write just 100 words per day, but 5 days a week, over the course of a year you’ll have produced 26,000 words. You don’t want to arrive to the end of your degree program or finish a bunch of analyses only to then start writing. You should be writing throughout the process. When I was ready to defend my PhD, I essentially stapled three papers together, used material from my proposal written years earlier to form the intro, and I then had a dissertation. There was no mad dash as the end to finish all the writing. I had done it already.  

How do you improve your writing? First, you have to write a lot. Second, you can read the work of others and take notes on the writing style. Why do you like how one paper is written compared to another? The best writers are also prolific readers. Third, you need to receive lots of feedback on your writing from me, your colleagues, and writing coaches/editors. On a given paper, I would expect us to go back and forth on 10+ drafts (even more with co-authors). The writing process is slow for this  reason.  
 

UNH writing resources 

https://gradschool.unh.edu/student-resources/career-professional-community-development-resources/writing-research 

All grad students can see a writing coach up to 8 times a semester!! Please do this.  

We also have paid professional editors that help our lab.  



General writing advice 

 

Advice on specific sections of a scientific paper 

Title 

Paper I wrote on scientific titles https://quantmarineecolab.github.io/pdfs/2023_Heard_etal_Facets.pdf 

Authors 

We have fairly clear authorship criteria in the lab (https://github.com/QuantMarineEcoLab/lab-onboarding/blob/main/qmel-onboarding.md#authorship), but they may not be the case when you work with external collaborators, so it is important to clarify authorship early in any project 

Abstract 

https://bpb-ap-se2.wpmucdn.com/sites.rmit.edu.au/dist/b/55/files/2018/04/Abstract-Guidelines-Nature-Journal-qip46l.pdf 

Introduction 

Methods 

Statistics/math 

P-values https://www.nature.com/articles/520612a 

Writing math ecology https://esajournals.onlinelibrary.wiley.com/doi/pdf/10.1002/ecs2.3701 

Results 

Discussion 

Conclusion 

Appendix 

Code 

Sharing code may result in more citations https://gradschool.unh.edu/student-resources/career-professional-community-development-resources/writing-research 

### Specific pieces of advice

- [How to write about regression outputs](https://doi.org/10.1111/2041-210X.12577)

## Where to publish 

A lot has been written on this topic. In general, we like to publish our work open access (which may be in the form of a preprint) and solid journals. The goal is to publish in the right journal as opposed to the "best journal possible". One useful tip is to go through your list of references. What journals do you cite? That probably gives you a good clue as to the write audience for your work. 

At UNH, we have a special [agreement with Cambridge](https://libraryguides.unh.edu/openaccess/memberships) to publish open access for free, including in the following journals.

- [Environmental Data Science](https://www.cambridge.org/core/journals/environmental-data-science)
- [Oryx](https://www.cambridge.org/core/journals/oryx)
- [Coastal Futures](https://www.cambridge.org/core/journals/cambridge-prisms-coastal-futures/overview-for-authors)
- [Environmental Conservation](https://www.cambridge.org/core/journals/environmental-conservation)

We also publish for free, or cheaply, in [PeerJ](https://peerj.com/) and UNH enjoys other [publishing discounts](https://libraryguides.unh.edu/openaccess/memberships).

### Submitting a paper 

Throughout the process of developing a paper for publication, you should also think about what journals you plan to submit to, who the co-authors will be, and when you want to submit. The answers to these questions will shape how you write the paper.  

Early in the development of a manuscript, you should have a target journal, determine the focus of the journal, and discuss with Easton or other senior authors. At this stage, you should have an ideal of the author list (and likely order) as well. It is important to sort out authorship very early in the process. 

At least 2-3 months prior to submission, you should have a full draft of the paper. After a round of revisions with the senior author(s), usually Easton, you can then get feedback from other co-authors. 

At least a month prior to submission, you should send the draft paper to all co-authors. You can do this in rounds, or send to everyone at once, but you should give every co-author at least three weeks to provide feedback. You should tell them a specific date by which you need their feedback.  

In addition to your co-authors, at this stage you should seek internally---often called “friendly” peer review. Before submission, all papers must be internally peer reviewed by a minimum of 2 QMEL lab members at the same level or higher than your current career stage. For example, if you are a graduate student, you can have your paper draft read by two other graduate students or a graduate student and a postdoc. This is an important step as co-authors can often be too close to the work and may miss important details.  

It is also useful to create an account at the journal you intend to submit. You can start the submission process to ensure you know what is expected from the journal. Each journal will also have an Author Guidelines document (see below for MEPS example). 

A week prior to submission, you should be incorporating edits from co-authors and discussing with the QMEL senior author on the paper. A week before submission, you should also email all co-authors to tell them that you plan to submit within a week and to ask if anyone objects to the final version of the manuscript. You should also tell them you plan to submit as a preprint if that applies to you.  

For submission, you need to carefully follow journal requirements. It is wise to review these requirements and create an author account with the journal well before you need to submit. These are outlined clearly on every journal website. Some journals require line numbers, a cover letter, a link to data, etc. You will almost certainly need to come up with a short list (usually 3-5 names) of potential paper reviewers to suggest. An editor won’t choose everyone on your list, but they often start there. You cannot suggest someone you have published with previously.  

  ## Authorship resources

-   <http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html>
-   <https://www.sciencemag.org/careers/2010/04/conventions-scientific-authorship>
-   <https://www.sciencemag.org/careers/2021/05/how-navigate-authorship-scientific-manuscripts>


Here is some other advice on submitting papers 

https://scientific-publishing.webshop.elsevier.com/publication-recognition/how-to-submit-a-paper-for-publication-in-a-journal/ 

https://medium.com/@aschrock/how-to-submit-a-journal-article-48bbca709c70 

### Acknowledgements (example with lots of details)

The authors would like to thank Josie DeMerit and Ella Williams for their assistance completing the laboratory experiments. We conducted data analysis of cardiac activity on the Premise High Performance Computing Cluster, supported by the University System of New Hampshire Research Computing Center and by New Hampshire-INBRE through an Institutional Development Award (IDeA), P20GM103506, from the National Institute of General Medical Sciences of the NIH. Field work and organism collection was completed under New Hampshire Fish and Game Department permit MFD 2430. This research was supported through grants to ARV by the New Hampshire Sea Grant Graduate Fellowship, and UNH School for Marine Science and Ocean Engineering (SMSOE) Graduate Student Fund. Additional funds were awarded by the New Hampshire Agricultural Experiment Station CREATE program through a joint funding program with the USDA National Institute of Food and Agriculture (Hatch award no. 7004018) and the State of New Hampshire. 
