# Money {#money}

## How money flows

## Funding

Like publications, funding is an important metric in science. Applying
for and receiving funding allows us to do interesting science, but it
also will help you in your career. As a lab member, you are expected to
apply for grants to support research and travel as well as fellowships
that may advance your career. This helps both you and the lab as a
whole. Although you’ll lead these applications, you can also expect
meaningful contributions from Easton throughout the process. This means
enough lead time is critical. In addition, you may occasionally be asked
to add comments or contribute a figure to a grant proposal that Easton
is working on. In addition, you are always welcome to read grants that
Easton has worked on or submitted.

As a lab, we have compiled a database of funding opportunities that are
the most relevant to members of this lab (see shared Google Drive).

### Types of Funding

#### TA-ship 

Teaching Assistants are hired to assist faculty in teaching undergraduate courses. Responsibilities may include, but are not limited to: classroom management and pedagogy, presentation of selected lectures, group discussion leadership, class organization and management tasks, and identification/organization of class resources. Teaching Assistants are mentored by faculty and receive constructive evaluative feedback concerning their pedagogy and teaching skills. 

Teaching assistants are expected to work no more than 20 hours per week. There could be an odd week here or there (e.g., during an exam week) that could be above 20, but other weeks should then be under 20 hours per week. If your hours are substantially under or at all over 20, please chat with Easton and the instructor of the course. No one should be having you serve as a TA for more than 20 hours a week. 

#### RA-ship 

Research Assistants are hired to assist faculty in research projects related to the faculty member’s area of expertise and research agenda. Responsibilities may include, but are not limited to: reviewing the literature, identify knowledge gaps, developing original research questions and survey instrumentation, data collection, data analyses and statistics, technical writing, peer-reviewed scientific writing, and refereed research presentations. Research Assistants are mentored by faculty and receive constructive evaluative feedback concerning their technical and research skills. 

A research assistantship can take a lot of different forms in the lab. A RA-ship during the academic year supports 20 hours per week of “research” time with the remaining 20 hours for your studies, coursework, etc. In the summer, all students are guaranteed 50% support (which is the same rate as you’re paid during the academic year). It is possible to get additional summer salary as well.  

In general, there are probably three different RA-ship scenarios within QMEL. Expectations should be set at the beginning of each semester between each student and Easton.  

The RA funds come from a grant that directly supports your graduate research (e.g., NSF grfp). The grant could be in the form of a grant or fellowship you apply for or from Easton  

The RA funds come from a project unrelated to your work. Here, you would be spending 20 hours a week working on some project with the remaining time dedicated to your own work and studies.  

A mix of the above 

For example:  

In 2024, Drew was on an RA-ship funded by a grant we received from the NH Agricultural Experimental Station. Drew spent about half of his time on research directly related to his dissertation and the other half on other work related to the grant. In this case, Drew was mentoring other students and setting up a field survey.  

In Summer 2023, Sophie was funded by two sources: a grant related to a project on lumpfish (unrelated to her thesis) and a fellowship she won. In that summer, she split her time between the two projects. Thus, the lumpfish project paid for some of her time even if it was unrelated to her thesis work.  

In Fall 2024, Selina had an RA ship through one of Easton’s grants. She spent 10-20 hours a week working on building biosensors, a project that wasn’t directly tied to her thesis. The rest of her time was focused on courses and her own research. 

During Fall 2024, Miguel was funded by a fellowship he won, the Fulbright. Thus, he is able to focus full time on his PhD work without being asked to do a lot of other lab responsibilities (e.g., lab or field work on other projects). He still attends lab meetings and is a good QMEL citizen, but most of his time is focused on research 

A student with their own funding* (e.g., Fulbright**, GRFP, STAF) has the most flexibility to focus their time on their own research projects. For example, if you were on a GRFP, Easton wouldn’t be allowed to ask you to work substantively on another project or TA.  

I would expect a student on an RA-ship to be more productive and more willing to help labmates that are on a TA-ship and are thus more limited in their own time.  

 

*Note. Scholarships usually come with their own terms and caveats. An agreement is made between UNH and the funding scholarship institution, but the grantee must keep track of paperwork and requirements from both institutions. Some scholarships come with tuition fee waivers, others expect grantees to apply for additional funding or have personal funds available. Scholarships rarely offer a summer stipend. Scholars MUST be full-time students (cover 9 credits each semester) for UNH to validate student benefits such as health insurance, regardless of the scholarship terms and support.  

**Fulbright Scholarship. Some students like Miguel, Salvador and Sophie have been Fullbright Scholars. Fulbright offers a fixed amount deposited in a couple installments through the academic year.  Scholars must give proof of funding covering cost of living and tuition estimates for their state. The scholarship will be reduced if the scholar receives funding from other sources. The only exception is what is called a “top-off award” given by the University or PI to match the scholar stipend to the minimum cost of living.    



 ### Funding Breakdowns

Summer funding models: 

Everyone is paid 50% time (around $7,500) each summer. The funding could be for your own work, but it could also be to help on other lab projects. 

If a student receives a grant, they can add it to their own summer salary 

If a student receives a grant, they can add some percent to summer salary where the rest would go to paying for overhead 

We collate all students grants and then distribute equally  

 

Let’s assume scenario 3.  

A STAF fellowship is $5,000 each summer. We could bump up a student salary to $9,600 (standard summer salary plus half of STAF). The remaining $2,500 would go to paying for other things in the lab 

Suppose a student gets a grant for $14,000 to their project. A student could apply the grant to bump them up by to full-time in the summer. Thus, they would make 7,000 from QMEL and 7,000 from their grant with the remaining 7,000 from the grant going back to cover QMEL expenses 

If a student received a $2,000 grant from SMSOE (or something similar), I could envision two scenarios: 

If unrestricted, then $1,000 would go to bumping up salary and another $1,000 would go to lab expenses 

If restricted to no salary, $2,000 could go to lab expenses, which may allow Easton to then bump up a student’s salary by $1,000 anyway 

If scenario 3, then we could have a diversity of salaries in the lab, despite everyone working a lot 

7,100 (50% time) 

14,000 (100% time) – grad student would need to bring in a grant of at least 14K to cover 50% of their top up with the rest going towards lab 

15 or 16K - NSF GRFP (or other fellowship) that goes to covering full salary 

## Grants/fellowships

- [Switzer fellowship](https://www.switzernetwork.org/fellowship/become-fellow)
