project: 
  type: book
  output-dir: _book
  
book:
  title: "Quantitative Marine Ecology Lab Manual"
  author: "Easton R. White"
  date: last-modified 
  description: "This is the lab manual for the Quantitative Marine Ecology Lab at the University of New Hampshire" 
  
  page-footer:
    left: |
      <a href="https://quantmarineecolab.github.io/">QuantMarineEcoLab</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://quantmarineecolab.github.io/lab-manual/
  repo-url: https://github.com/QuantMarineEcoLab/lab-manual
  repo-actions: [edit,issue]

  chapters: 
    - index.qmd
    - 01-intro-how-we-work.qmd
    - 02-lab-culture-philosophy.qmd
    - 03-code-of-conduct.qmd
    - 04-recruitment.qmd
    - 05-onboarding.qmd
    - 06-training-undergrads-and-interns.qmd
    - 07-training-grad-students.qmd
    - 08-training-postdocs-and-staff.qmd
    - 09-training-lab-leader.qmd
    - 10-producing-quality-work.qmd
    - 11-scicomm-and-outreach.qmd
    - 12-grants.qmd
    - 13-money.qmd
    - 14-offboarding.qmd
    - 15-UNH-and-Durham.qmd
    - 16-lab-manual-inspiration.qmd
    - 17-helpful-links.qmd



# not sure what the following line does; those files are present
bibliography: [references.bib, book.bib]

