project: 
  type: book
  output-dir: _book
  
book:
  title: "Quantitative Marine Ecology Lab Manual"
  author: "Easton R. White"
  date: last-modified 
  description: "This is the lab manual for the Quantitative Marine Ecology Lab at the University of New Hampshire" 
  
  page-footer:
    left: |
      <a href="https://quantmarineecolab.github.io/">QuantMarineEcoLab</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://quantmarineecolab.github.io/lab-manual/
  repo-url: https://github.com/QuantMarineEcoLab/lab-manual
  repo-actions: [edit,issue]

  chapters: 
    - index.qmd
    - 01-intro-how-we-work.qmd
    - 02-lab-culture-philosophy.qmd
    - 03-code-of-conduct.qmd
    - 04-onboarding.qmd
    - 05-expectations.qmd
    - 06-offboarding.qmd
    - 07-funding.qmd
    - 08-communication.qmd
    - 09-academics.qmd
    - 10-courses.qmd
    - 11-computing.qmd
    - 12-umassd-resources.qmd
#    - 13-smast-resources.qmd
#    - 14-other-faylab-resources.qmd  


# not sure what the following line does; those files are present
bibliography: [references.bib, book.bib]

